#@ load("@ytt:data", "data")

apiVersion: apps/v1
kind: Deployment
metadata:
  name: #@ data.values.name
  namespace: #@ data.values.namespace
spec:
  replicas: #@ data.values.replicas
  template:
    spec:
      containers:
      - name: default
        ports:
        - containerPort: #@ data.values.port
        image: #@ data.values.image
        args:
        - #@ "-listen=:{}".format(data.values.port)
        - '-text=Hello World'
        
---
kind: Service
apiVersion: v1
metadata:
  name: echo-service
  namespace: #@ data.values.namespace
spec:
  #@ if hasattr(data.values,"service_type"):
  type: #@ data.values.service_type
  #@ end
  ports:
  - name: echo-first
    port: #@ data.values.port
